# Generated by Django 4.0.6 on 2022-07-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('trabajo', models.CharField(max_length=50)),
                ('nacimiento', models.DateField(max_length=30)),
                ('dni', models.IntegerField()),
            ],
        ),
    ]
